-- define primary key at column level
CREATE TABLE students (
    student_id INTEGER PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(150)
);

-- define primary key at table level
CREATE TABLE students (
    student_id INTEGER,
    name VARCHAR(100),
    email VARCHAR(150),
    PRIMARY KEY (student_id)
);

-- define primary key with a custom name
CREATE TABLE students (
    student_id INTEGER,
    name VARCHAR(100),
    email VARCHAR(150),
    CONSTRAINT pk_students PRIMARY KEY (student_id)
);

-- add primary key to existing table
ALTER TABLE students ADD CONSTRAINT pk_students PRIMARY KEY (student_id);

-- single primary key
CREATE TABLE students (
    student_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE,
    faculty VARCHAR(50)
);

--- insert sample data
INSERT INTO students (name, email, faculty) VALUES
('Alice Johnson', 'alice@auca.kg', 'Software Engineering'),
('Bob Smith', 'bob@auca.kg', 'Mathematics'),
('Carol Davis', 'carol@auca.kg', 'Software Engineering');

-- composite primary key
CREATE TABLE course_enrollments (
    student_id INTEGER,
    course_id INTEGER,
    semester VARCHAR(20),
    enrollment_date DATE DEFAULT CURRENT_DATE,
    grade CHAR(2),
    PRIMARY KEY (student_id, course_id, semester)
);

--- insert sample data
INSERT INTO course_enrollments (student_id, course_id, semester, grade) VALUES
(1, 101, '2024-Spring', 'A'),
(1, 102, '2024-Spring', 'B+'),
(2, 101, '2024-Spring', 'A-'),
(1, 101, '2024-Fall', 'A+');  -- Same student can take same course in different semester

-- automatic number generation (AUTO_INCREMENT equivalent)
--- SERIAL
CREATE TABLE products (
    product_id SERIAL PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    price DECIMAL(10,2)
);

/*  SERIAL is equivalent to:
    product_id INTEGER NOT NULL DEFAULT nextval('products_product_id_seq'),
    where products_product_id_seq is an automatically created sequence */

--- BIGSERIAL
CREATE TABLE transactions (
    transaction_id BIGSERIAL PRIMARY KEY,  -- Can handle very large numbers
    amount DECIMAL(15,2),
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--- IDENTITY Columns
---- IDENTITY ALWAYS - PostgreSQL controls the value completely
CREATE TABLE orders (
    order_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(100),
    order_date DATE DEFAULT CURRENT_DATE
);

---- IDENTITY BY DEFAULT - Allows manual insertion but auto-generates if not provided
CREATE TABLE customers (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(100),
    email VARCHAR(150)
);

---- You can still insert specific values with BY DEFAULT
INSERT INTO customers (customer_id, customer_name, email)
VALUES (1000, 'VIP Customer', 'vip@example.com');

-- UNIQUE Primary key constraint
CREATE TABLE departments (
    dept_id INTEGER PRIMARY KEY,
    dept_name VARCHAR(100)
);

--- This will fail due to duplicate primary key
INSERT INTO departments VALUES (1, 'Computer Science');
INSERT INTO departments VALUES (1, 'Mathematics'); -- ERROR: duplicate key value

-- NOT NULL Primary key constraint
--- This will fail because primary key cannot be NULL
INSERT INTO departments VALUES (NULL, 'Physics'); -- ERROR: null value in column "dept_id"